[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  # 移除强制禁用Netlify Runtime的设置
  # NETLIFY_USE_NEXT_RUNTIME = "false"
  NODE_VERSION = "18"

# 恢复Netlify Next.js插件
# [[plugins]]
#   package = "@netlify/plugin-nextjs"

# 移除静态站点的 /* -> index.html 重定向
# [[redirects]]
#   from = "/*"
#   to = "/index.html"
#   status = 200

# 保留对revalidation的重定向（如果仍然需要）
[[redirects]]
  from = "/revalidation"
  to = "/"
  status = 301
  force = true 