name: SQL Script Cron Job

on:
  schedule:
    - cron: "0 19 * * *" # 每天 UTC 19:00 (美国中部时间 14:00)
  workflow_dispatch:

env:
  DATABASE_URL: ${{ secrets.DATABASE_URL }}
  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

jobs:
  run-sql-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Create environment file
        run: |
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> .env.local
          echo "SLACK_WEBHOOK_URL=${{ secrets.SLACK_WEBHOOK_URL }}" >> .env.local
          echo "MONGODB_URI=${{ secrets.MONGODB_URI }}" >> .env.local
          echo "NODE_ENV=production" >> .env.local

      - name: Debug directory structure
        run: |
          pwd
          ls -la
          ls -la scripts/
          ls -la scripts/sql_scripts/
          echo "--- .env.local content start ---"
          cat .env.local || echo ".env.local not found or empty"
          echo "--- .env.local content end ---"

      - name: Run SQL Check Script
        env:
          DOTENV_CONFIG_PATH: .env.local 
        run: |
          echo "Current working directory: $(pwd)"
          echo "Using .env file: ${DOTENV_CONFIG_PATH}"
          ls -la ${DOTENV_CONFIG_PATH}
          echo "About to execute ts-node..."
          # Use ts-node with -r to preload dotenv/config
          npx ts-node -r dotenv/config scripts/run-sql.ts check-square-order-duplicates
        continue-on-error: false
