name: SQL Script Cron Job

on:
  schedule:
    - cron: "0 19 * * *" # 每天 UTC 7 PM
  workflow_dispatch:

env:
  DATABASE_URL: ${{ secrets.DATABASE_URL }}
  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

jobs:
  run-sql-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Create environment file
        run: |
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> .env.local
          echo "SLACK_WEBHOOK_URL=${{ secrets.SLACK_WEBHOOK_URL }}" >> .env.local
          echo "NODE_ENV=production" >> .env.local

      - name: Debug directory structure
        run: |
          pwd
          ls -la
          ls -la scripts/
          ls -la scripts/sql_scripts/

      - name: Run SQL Script
        run: |
          echo "当前工作目录: $(pwd)"
          echo "使用新的入口脚本执行"
          npx ts-node scripts/sql_scripts/run_script.ts check_square_order_duplicates
        continue-on-error: false
